### PR TITLE
Hotfix interim

### PR DESCRIPTION
**Pull request by michaeltryby**
Changes: 
This PR makes changes to fix several problems with the current wheel build and actions workflows:
 - Linux wheels were being broken when audited and made manylinux compliant
 - Version of libomp being packaged in the MacOS wheel was not binary compatible with Python
 - Path issues were causing missing libraries at runtime
 - Package name "swmm-toolkit" is not PEP 8, PEP 423 compliant
 - Pin dependency aenum==2.2.6 as workaround for regression in aenum v3.0 

Justification:
Several problems with the swmm-toolkit v0.8.1 wheels have been identified. These fixes have already been approved and merged into the develop branch. They are being recast as a hotfix PR to facilitate release of an updated v0.8.2 wheel.

### CODE REVIEW

**Comment by jennwuu** [comment]
@michaeltryby do you want to include string byte temp. workaround in this PR as well?

**Comment by michaeltryby** [comment]
@jennwuu I think that fix fits better in pyswmm. Can you make it there?

**Review by jennwuu — APPROVED** [review]

**Comment by jennwuu** [comment]
confirmed that anaconda works on anaconda as well

**Comment by jennwuu** [comment]
@michaeltryby Is this PR merge ready?

**Comment by michaeltryby** [comment]
@jennwuu this PR is ready unless you want to address the unicode path issue.

**Comment by jennwuu** [comment]
@michaeltryby Looks like we can merge this PR and make an interim release on python pypi without needing to make any change for unicode path. Thanks for figuring this issue and finding a workaround!

**Pull request merged**
