### PR TITLE
Dev rename

### PR DESCRIPTION
**Pull request by michaeltryby**
Proposed function renames. Please review.

### CODE REVIEW

**Comment by michaeltryby** [comment]
I noticed that there are some potential duplicate functions. Please have a look to help me determine if they are in fact duplicates and decide what to do about them.

**Review by cbuahin — COMMENTED** [review]
Looks good to me!

**Review by cbuahin — APPROVED** [review]
Looks good.

**Comment by michaeltryby** [comment]
@cbuahin Thanks for the review!

**Review by jennwuu — APPROVED** [review]
The function names look good to me. Thanks!

**Comment by michaeltryby** [comment]
Thanks for the reviews @cbuahin and @jennwuu. I'm going to merge to make way for another PR focused on getting docs in shape. Thanks!

**Pull request merged**
