### PR TITLE
fix to get add_dll_directory working on conda-built python distributions

### PR DESCRIPTION
**Pull request by karosc**
Addresses #79 . 

I also revised the nrtest-swmm output_reader.py file to import shared_enum rather than output_enum since the file was renamed and the import no longer works.

### CODE REVIEW

**Review by michaeltryby — APPROVED** [review]
Thanks for identifying and fixing this issue! We really appreciate it!

**Review by jennwuu — APPROVED** [review]
Looks good to me!

**Comment by karosc** [comment]
Thank you both for being so responsive!

**Comment by michaeltryby** [comment]
@karosc I'm updating the contributor information for the project. Could you please forward your email address so we can contact you in the future if necessary? Thanks!

**Comment by karosc** [comment]
ckaros@outlook.com

**Comment by michaeltryby** [comment]
Thanks @karosc!

**Pull request merged**
