### PR TITLE
Build wheels on github Actions

### PR DESCRIPTION
**Pull request by lrntct**
Automatically builds on macOS, manylinux and Windows using cibuildwheel and GH Actions.

### CODE REVIEW

**Comment by lrntct** [comment]
@michaeltryby it seems that there is an issue during cmake. Any clue?

```
CMake Error at /opt/_internal/cpython-3.7.7/lib/python3.7/site-packages/cmake/data/share/cmake-3.17/Modules/UseSWIG.cmake:716 (add_library):
    Target "solver" links to target "Python::Module" but the target was not
    found.  Perhaps a find_package() call is missing for an IMPORTED target, or
    an ALIAS target is missing?
  Call Stack (most recent call first):
    src/swmm/toolkit/CMakeLists.txt:93 (swig_add_library)
```
https://github.com/lrntct/swmm-python/runs/829138273

Also, the build is supposed to be triggered on PR, but I do not see this happen here. Do you know how to solve this?

**Comment by michaeltryby** [comment]
Swig wrapper uses Python C API so it is a link dependency. The error is because cmake can’t find the python library. If you refer to cmake find python documentation Im sure there is a way to provide a hint where cmake should look.

**Comment by lrntct** [comment]
@michaeltryby I managed to build the wheel on Windows, but the tests fail:
https://github.com/lrntct/swmm-python/runs/856456618

It fails to import "swmm". I can reproduce the issue on my local machine. It means that the install fails and it is therefore a bigger issue that just the CI.
Is this a known issue?

**Comment by lrntct** [comment]
@michaeltryby about the issue of not finding the python includes, it is very surprising. It is a docker image especially designed to build Python wheels. And it was working in https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/284

**Comment by michaeltryby** [comment]
> @michaeltryby I managed to build the wheel on Windows, but the tests fail:
> https://github.com/lrntct/swmm-python/runs/856456618
> 
> It fails to import "swmm". I can reproduce the issue on my local machine. It means that the install fails and it is therefore a bigger issue that just the CI.
> Is this a known issue?

@lrntct Looks like you are making good progress! The unit tests for the swmm-toolkit package are located in `swmm-python/swmm-toolkit/tests`. The `swmm-python/tests` folder can be deleted. It's a test for an edge case that has served its purpose. 

That said, `from swmm.toolkit import solver` should be working so there is some problem with the wheel. It's hard to say what is going on from the logs. Is there a way to make logs more verbose or upload the wheel as an artifact to provide more information for trouble shooting the problem? 

Also noticed Visual Studio 2017 install. VS2017 is preinstalled on the `windows-2016` image. There is an open issue with GitHub Actions dev team to add Visual Studio 2015 as well. But it might take awhile.

**Comment by michaeltryby** [comment]
> @michaeltryby about the issue of not finding the python includes, it is very surprising. It is a docker image especially designed to build Python wheels. And it was working in [OpenWaterAnalytics/Stormwater-Management-Model#284](https://github.com/OpenWaterAnalytics/Stormwater-Management-Model/pull/284)

@lrntct Like I said, it's hard to say at this point what exactly is causing the import to fail given the information available.

**Comment by michaeltryby** [comment]
@lrntct Thanks for your work on this! We have made progress on setting up the build system on swmm repo and SWIG wrapping the toolkit API in the swmm-python repo. We are ready to automate the wheel build using this PR.

**Comment by michaeltryby** [comment]
The wheel build has been successfully implemented and is currently in production. Thanks for your contribution to the project.

**Pull request closed without merging**
